environments:
  dev:
    gcs_bucket: airflow-dev

  prod:
    gcs_bucket: airflow-prod

apis:
  spotify:
    auth: oauth2
    base_url: https://api.spotify.com/v1/
    token_url: https://accounts.spotify.com/api/token
    default_headers:
      Accept: application/json
    paths:
      songs:
        endpoint: /tracks/{song_id}
      artists:
        endpoint: artists/{artist_id}

  tmdb:
    auth: api_key
    base_url: https://api.themoviedb.org/3/
    default_headers:
      Accept: application/json
    paths:
      movies:
        endpoint: /movie/{movie_id}
      movies_credits:
        endpoint: /movie/{movie_id}/credits
      discover_movies:
        endpoint: /discover/movie